#!/bin/bash
rm /etc/udev/rules.d/aic.rules
udevadm control --reload
rm /usr/local/bin/usb-eject-delay.sh
echo "Uninstall aic8800 wifi driver!!!!!"
rmmod aic8800_fdrv
rmmod aic_load_fw
cd /usr/src/AIC8800/drivers/aic8800/aic8800_fdrv/
make clean
make uninstall
cd /usr/src/AIC8800/drivers/aic8800/aic_load_fw/
make clean
make uninstall
cd /usr/src/AIC8800/aicrf_test
make clean
rm -rf /lib/firmware/aic8800D80/
rm -rf /usr/src/AIC8800/
rm -rf /AIC8800/
#exit 0
